<div class="row">
    <div class="col-sm-12">
        <h1>Documentation</h1>
        <p>Imbo has two types of documentation available. End-user docs, and API docs.</p>
    </div>
    <div class="col-sm-6">
        <h2>End-user docs</h2>
        <p>Imbo's end-user docs is hosted over at the readthedocs.org site, and is most likely what you are looking for.</p>
        <p><a class="btn btn-success" href="http://docs.imbo-project.org">End-user docs &raquo;</a></p>
    </div>
    <div class="col-sm-6">
        <h2>API docs</h2>
        <p>Imbo's API docs is for those of you looking to extend Imbo with custom event listeners or some other goodies.</p>
        <p><a class="btn btn-success" href="http://docs.imbo-project.org">API docs &raquo;</a></p>
    </div>
</div>
