<div class="row">
    <div class="col-lg-12">
        <h2>Additional information:</h2>
        <?= $this->partial('error/exceptionInfo', array('exception' => $exception)) ?>
        <?php $e = $exception->getPrevious(); ?>
        <?php if ($e) { ?>
        <hr>
        <h2>Previous exceptions:</h2>
        <ul class="list-unstyled">
            <?php while($e) { ?>
            <li><?= $this->partial('error/exceptionInfo', array('exception' => $e)) ?></li>
            <?php $e = $e->getPrevious(); ?>
            <?php } ?>
        </ul>
        <?php } ?>
    </div>
</div>
